"""17.08.2023-00:12:36

Revision ID: 250659ceadfb
Revises: 1d63889d97e4
Create Date: 2023-08-17 00:12:37.075757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '250659ceadfb'
down_revision = '1d63889d97e4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
